version: "3"
services:
  cloudera:
    container_name: cloudera
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: cloudera/quickstart
    hostname: quickstart
    domainname: cloudera
    ports:
      - "8888:8888"
      - "10000:10000"
      - "10020:10020"
      - "11000:11000"
      - "18080:18080"
      - "18081:18081"
      - "18088:18088"
      - "19888:19888"
      - "21000:21000"
      - "21050:21050"
      - "2181:2181"
      - "25000:25000"
      - "25010:25010"
      - "25020:25020"
      - "50010:50010"
      - "50030:50030"
      - "50060:50060"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030" 
      - "7180:7180"
      - "7183:7183"
      - "7187:7187" 
      - "8889:80" # tutorial http://localhost:8889
      - "8020:8020"
      - "8032:8032"
      - "802:8042"
      - "8088:8088"
      - "8983:8983"
      - "9083:9083"
    entrypoint: "/usr/bin/docker-quickstart"
    volumes:
      - cloudera-hdfs-name:/var/lib/hadoop-hdfs/cache/hdfs/dfs/name
      - cloudera-hdfs-data:/var/lib/hadoop-hdfs/cache/hdfs/dfs/data
      - ./docker-quickstart:/usr/bin/docker-quickstart:ro

volumes:
  cloudera-hdfs-name:
  cloudera-hdfs-data: